### ISSUE TITLE
Wrong scaling in portrait mode on mobile after flipping to landscape

### ISSUE THREAD

**Issue by davethecipo** [mhkeller/pulp2#5] opened 2016-11-30 21:13 UTC
Hi, I've just discovered this project and looks awesome.

I'm testing it with Chrome 54 on Android 5. 

Steps to reproduce:
- open the page in portrait mode
- flip the phone to activate landscape mode (this changes the layout to double page)
- flip back to portrait

What I expect: when going back to portrait, it should re-activate the mobile view
What happens: when going back to portrait, the double page view remains (tapping to zoom doesn't work)

**Comment by mhkeller** [comment] 2017-03-08 01:05
Hi @davethecipo, thanks for opening this. I think this is the same issue as https://github.com/mhkeller/pulp2/issues/6 where it isn't detecting the proper size after the screen gets taller.

**Comment by mhkeller** [comment] 2017-03-08 02:13
@davethecipo I just tested and this should be fixed now, give it a try and I'll close.

**Comment by Globulle** [comment] 2017-03-26 17:49
As far as I'm concerned, the issue is solved.

**Closed** 2017-03-26 21:08 UTC

**Comment by davethecipo** [comment] 2017-03-27 16:13
Oh crap, sorry not answering! Thanks for the fix
